# Generated by Django 5.0.9 on 2024-09-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('Cod_identif', models.CharField(max_length=15, unique=True, verbose_name='Carne')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'UserSystem',
                'ordering': ['id'],
            },
        ),
    ]
