# Generated by Django 5.0.9 on 2024-09-09 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDPv2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoSede', models.CharField(max_length=15, unique=True, verbose_name='CodigoSede')),
                ('municipio', models.CharField(max_length=60)),
                ('departamento', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'sede',
                'verbose_name_plural': 'Sedes_Universidad',
                'db_table': 'sede',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDoc', models.CharField(max_length=300, unique=True, verbose_name='NombreTesis')),
                ('estado', models.CharField(max_length=60)),
                ('fechaAprobado', models.DateField()),
                ('enlaceDOI', models.URLField()),
                ('fechaPublicado', models.DateField()),
                ('autor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SDPv2.user')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'db_table': 'documento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='docHTML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_html_original', models.CharField(max_length=200)),
                ('html_sistema', models.TextField()),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SDPv2.documento')),
            ],
            options={
                'verbose_name': 'docHTML',
                'verbose_name_plural': 'docsHTML',
                'db_table': 'docHTML',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='otherUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SDPv2.user')),
            ],
            options={
                'verbose_name': 'OtherUser',
                'verbose_name_plural': 'Other_Users',
                'db_table': 'OtherUser',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='caseCreateUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='fechaCaso')),
                ('id_Otheruser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SDPv2.otheruser')),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'db_table': 'Case',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='proffessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SDPv2.user')),
            ],
            options={
                'verbose_name': 'Proffessor',
                'verbose_name_plural': 'Docentes',
                'db_table': 'Proffessor',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoCurso', models.CharField(max_length=15, unique=True, verbose_name='CodigoSede')),
                ('idProffessor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SDPv2.proffessor')),
                ('idSede', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SDPv2.sede')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'Curso',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('cursoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SDPv2.curso')),
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SDPv2.user')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'Estudiante',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='userAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SDPv2.user')),
            ],
            options={
                'verbose_name': 'userAuth',
                'verbose_name_plural': 'Users_Authorization',
                'db_table': 'userAuth',
                'ordering': ['id'],
            },
        ),
    ]
