# Generated by Django 5.0.9 on 2024-09-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDPv2', '0003_remove_user_fecha_creado_documento_documento_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.TextField(default=1, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
