# Generated by Django 5.0.9 on 2024-09-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDPv2', '0004_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(verbose_name='Username'),
        ),
    ]
