# Generated by Django 5.0.9 on 2024-09-25 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SDPv2', '0005_user_fecha_creado_alter_user_username'),
    ]

    operations = [
    ]
