# Generated by Django 5.0.9 on 2024-09-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDPv2', '0006_remove_user_fecha_creado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=25, unique=True, verbose_name='Username'),
        ),
    ]
