# Generated by Django 5.0.9 on 2024-09-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDPv2', '0007_alter_user_username'),
    ]

    operations = [
    ]
