# Generated by Django 5.0.9 on 2024-09-25 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SDPv2', '0008_user_fecha_creado_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='nombreUsuario',
        ),
    ]
