# Generated by Django 5.0.9 on 2024-09-26 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SDPv2', '0009_rename_username_user_nombreusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nombreUsuario',
        ),
    ]
