# Generated by Django 5.0.9 on 2024-09-26 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SDPv2', '0010_remove_user_nombreusuario'),
    ]

    operations = [
    ]
