# Generated by Django 5.0.9 on 2024-09-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDPv2', '0011_remove_user_fecha_creado'),
    ]

    operations = [
    ]
