# Generated by Django 5.0.9 on 2024-09-26 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SDPv2', '0012_user_fecha_creado_user_username'),
    ]

    operations = [
    ]
