# Generated by Django 5.0.9 on 2024-09-26 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SDPv2', '0013_remove_user_username'),
    ]

    operations = [
    ]
