# Generated by Django 5.0.9 on 2024-09-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDPv2', '0017_tesisdetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesisdetalle',
            name='path',
            field=models.TextField(default=1, verbose_name='Path'),
            preserve_default=False,
        ),
    ]
