# Generated by Django 5.0.9 on 2024-09-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDPv2', '0018_tesisdetalle_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesisdetalle',
            name='vector_palabras',
            field=models.JSONField(blank=True, null=True, verbose_name='Vector de palabras clave'),
        ),
    ]
